/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diffie.hellmankeyexchange;

import java.math.BigInteger;

/**
 *
 * @author Dajne Win
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        testButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aliceTextArea = new javax.swing.JTextArea();
        bobTextArea = new javax.swing.JScrollPane();
        bobTxtArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        eveTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Alice");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Bob");

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        aliceTextArea.setColumns(20);
        aliceTextArea.setRows(5);
        jScrollPane1.setViewportView(aliceTextArea);

        bobTxtArea.setColumns(20);
        bobTxtArea.setRows(5);
        bobTextArea.setViewportView(bobTxtArea);

        eveTextArea.setColumns(20);
        eveTextArea.setRows(5);
        jScrollPane2.setViewportView(eveTextArea);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Eve");

        jButton1.setText("MTM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Rand");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testButton)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bobTextArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(bobTextArea)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(testButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed

        aliceTextArea.setText("");
        bobTxtArea.setText("");
        eveTextArea.setText("");
        long g = 10;
        long p = 541;
        BigInteger pBig = BigInteger.valueOf(p);
        aliceTextArea.append("g = " + g + ", p = " + p + "\n\r");
        bobTxtArea.append("g = " + g + ", p = " + p + "\n\r");
        int a = 7;
        int b = 13;
        aliceTextArea.append("a = " + a + "\n\r");
        bobTxtArea.append("b = " + b + "\n\r");
        double A = Math.pow(g, a)%p;
        double B = Math.pow(g, b)%p;
        aliceTextArea.append("A = g^a mod p = " + g + "^" + a + " mod " + p + " = " + A + "\n\r");
        bobTxtArea.append("B = g^b mod p = " + g + "^" + b + " mod " + p + " = " + B + "\n\r");
        aliceTextArea.append("Bob has sent his public key B = " + B + "\n\r");
        bobTxtArea.append("Alice has sent her public key A = " + A + "\n\r");
        //double privateKeyA = Math.pow(B, a)%p;
        //double privateKeyB = Math.pow(A, b)%p;
        BigInteger privateKeyA = BigInteger.valueOf(g);
        privateKeyA = privateKeyA.pow(b);
        privateKeyA = privateKeyA.mod(pBig);
        privateKeyA = privateKeyA.pow(a);
        privateKeyA = privateKeyA.mod(pBig);
        
        BigInteger privateKeyB = BigInteger.valueOf(g);
        privateKeyB = privateKeyB.pow(a);
        privateKeyB = privateKeyB.mod(pBig);
        privateKeyB = privateKeyB.pow(b);
        privateKeyB = privateKeyB.mod(pBig);
                
        aliceTextArea.append("Private Key = B^a mod p = " + B + "^" + a + " mod " + p + " = " + privateKeyA + "\n\r");
        bobTxtArea.append("Private Key = A^b mod p = " + A + "^" + b + " mod " + p + " = " + privateKeyB + "\n\r");
        
        eveTextArea.append("g = " + g + "\n\r");
        eveTextArea.append("p = " + p + "\n\r");
        eveTextArea.append("A = " + A + "\n\r");
        eveTextArea.append("B = " + B + "\n\r");
    }//GEN-LAST:event_testButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        aliceTextArea.setText("");
        bobTxtArea.setText("");
        eveTextArea.setText("");
        long AliceG = 10;
        long AliceP = 541;
        BigInteger AlicepBig = BigInteger.valueOf(AliceP);
        aliceTextArea.append("(Alice)g = " + AliceG + ", (Alice)p = " + AliceP + "\n\r");
        eveTextArea.append("(Alice)g = " + AliceG + ", (Alice)p = " + AliceP + "\n\r");
        
        long BobG = 20;
        long BobP = 997;
        BigInteger BobpBig = BigInteger.valueOf(BobP);
        bobTxtArea.append("(Bob)g = " + BobG + ", (Bob)p = " + BobP + "\n\r");
        eveTextArea.append("(Bob)g = " + BobG + ", (Bob)p = " + BobP + "\n\r");
        
        int a = 43;
        int b = 53;
        aliceTextArea.append("a = " + a + "\n\r");
        eveTextArea.append("b = " + b + "\n\r");
        double A = Math.pow(AliceG, a)%AliceP;
        double B = Math.pow(AliceG, b)%AliceP;
        aliceTextArea.append("A = g^a mod p = " + AliceG + "^" + a + " mod " + AliceP + " = " + A + "\n\r");
        eveTextArea.append("B = g^b mod p = " + AliceG + "^" + b + " mod " + AliceP + " = " + B + "\n\r");
        aliceTextArea.append("(Eve)Bob has sent his public key B = " + B + "\n\r");
        eveTextArea.append("Alice has sent her public key A = " + A + "\n\r");
        BigInteger privateKeyA = BigInteger.valueOf(AliceG);
        privateKeyA = privateKeyA.pow(b);
        privateKeyA = privateKeyA.mod(AlicepBig);
        privateKeyA = privateKeyA.pow(a);
        privateKeyA = privateKeyA.mod(AlicepBig);
        
        BigInteger privateKeyB = BigInteger.valueOf(AliceG);
        privateKeyB = privateKeyB.pow(a);
        privateKeyB = privateKeyB.mod(AlicepBig);
        privateKeyB = privateKeyB.pow(b);
        privateKeyB = privateKeyB.mod(AlicepBig);
        
        aliceTextArea.append("Private Key = B^a mod p = " + B + "^" + a + " mod " + AliceP + " = " + privateKeyA + "\n\r");
        eveTextArea.append("(Alice)Private Key = A^b mod p = " + A + "^" + b + " mod " + AliceP + " = " + privateKeyB + "\n\r");
        
        a = 89;
        b = 101;
        bobTxtArea.append("a = " + a + "\n\r");
        eveTextArea.append("b = " + b + "\n\r");
        A = Math.pow(BobG, a)%BobP;
        B = Math.pow(BobG, b)%BobP;
        bobTxtArea.append("A = g^a mod p = " + BobG + "^" + a + " mod " + BobP + " = " + A + "\n\r");
        eveTextArea.append("B = g^b mod p = " + BobG + "^" + b + " mod " + BobP + " = " + B + "\n\r");
        bobTxtArea.append("(Eve)Alice has sent her public key B = " + B + "\n\r");
        eveTextArea.append("Bob has sent his public key A = " + A + "\n\r");
        privateKeyA = BigInteger.valueOf(BobG);
        privateKeyA = privateKeyA.pow(b);
        privateKeyA = privateKeyA.mod(BobpBig);
        privateKeyA = privateKeyA.pow(a);
        privateKeyA = privateKeyA.mod(BobpBig);
        
        privateKeyB = BigInteger.valueOf(BobG);
        privateKeyB = privateKeyB.pow(a);
        privateKeyB = privateKeyB.mod(BobpBig);
        privateKeyB = privateKeyB.pow(b);
        privateKeyB = privateKeyB.mod(BobpBig);
        
        bobTxtArea.append("Private Key = B^a mod p = " + B + "^" + a + " mod " + AliceP + " = " + privateKeyA + "\n\r");
        eveTextArea.append("(Bob)Private Key = A^b mod p = " + A + "^" + b + " mod " + AliceP + " = " + privateKeyB + "\n\r");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        aliceTextArea.setText("");
        bobTxtArea.setText("");
        eveTextArea.setText("");
        long g = 10;
        long p = 541;
        BigInteger pBig = BigInteger.valueOf(p);
        aliceTextArea.append("g = " + g + ", p = " + p + "\n\r");
        bobTxtArea.append("g = " + g + ", p = " + p + "\n\r");
        int a = 7;
        int b = 13;
        aliceTextArea.append("a = " + a + "\n\r");
        bobTxtArea.append("b = " + b + "\n\r");
        double A = Math.pow(g, a)%p;
        double B = Math.pow(g, b)%p;
        aliceTextArea.append("A = g^a mod p = " + g + "^" + a + " mod " + p + " = " + A + "\n\r");
        bobTxtArea.append("B = g^b mod p = " + g + "^" + b + " mod " + p + " = " + B + "\n\r");
        aliceTextArea.append("Bob has sent his public key B = " + B + "\n\r");
        bobTxtArea.append("Alice has sent her public key A = " + A + "\n\r");
        //double privateKeyA = Math.pow(B, a)%p;
        //double privateKeyB = Math.pow(A, b)%p;
        BigInteger privateKeyA = BigInteger.valueOf(g);
        privateKeyA = privateKeyA.pow(b);
        privateKeyA = privateKeyA.mod(pBig);
        privateKeyA = privateKeyA.pow(a);
        privateKeyA = privateKeyA.mod(pBig);
        
        BigInteger privateKeyB = BigInteger.valueOf(g);
        privateKeyB = privateKeyB.pow(a);
        privateKeyB = privateKeyB.mod(pBig);
        privateKeyB = privateKeyB.pow(b);
        privateKeyB = privateKeyB.mod(pBig);
                
        aliceTextArea.append("Private Key = B^a mod p = " + B + "^" + a + " mod " + p + " = " + privateKeyA + "\n\r");
        bobTxtArea.append("Private Key = A^b mod p = " + A + "^" + b + " mod " + p + " = " + privateKeyB + "\n\r");
        
        eveTextArea.append("g = " + g + "\n\r");
        eveTextArea.append("p = " + p + "\n\r");
        eveTextArea.append("A = " + A + "\n\r");
        eveTextArea.append("B = " + B + "\n\r");
        
        eveTextArea.append("I know Bob's private key is between 1-20" + "\n\r");
        eveTextArea.append("I know Bob's private key is prime!" + "\n\r");
        eveTextArea.append("Try: 2, 3, 5, 7, 11, 13, 17, 19" + "\n\r");
        eveTextArea.append("13 Appears to work!" + "\n\r");
        eveTextArea.append("Private Key = A^b mod p = " + A + "^" + b + " mod " + p + " = " + privateKeyB + "\n\r");
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea aliceTextArea;
    public javax.swing.JScrollPane bobTextArea;
    public javax.swing.JTextArea bobTxtArea;
    public javax.swing.JTextArea eveTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables
}
